### ISSUE TITLE
报错! Undefined control sequence. l.67 \CJKaddEncHook                    {Bg5}{\CJK@traditionalNumbers} ? 

### ISSUE THREAD

**Issue by lymzzu** [sijichun/sufethesis#1]
你好，window系统，字体改过了。出现报错如下
Undefined control sequence. l.67 \CJKaddEncHook                    {Bg5}{\CJK@traditionalNumbers} ? 
当我在cls中去掉\usepackage{CJKnumb}
又出现
<img width="393" alt="1635393012(1)" src="https://user-images.githubusercontent.com/35551043/139183489-f1211596-5e56-4294-8b40-7e060ab77b52.png">

**Comment by sijichun** [comment]
用xelatex
