### ISSUE TITLE
overleaf使用

### ISSUE THREAD

**Issue by zhenweilin** [sijichun/sufethesis#2]
overleaf 使用如下
1. 修改合适字体
2. 将编译器修改为 xelatex
3. 修改为 2021版本或之前的编译器

仍然会出现 `You can't pop an empty literal stack for entry` 的错误

**Comment by zhenweilin** [comment]
已经fix, 是由于bib的那个字段信息不全, Google scholar中的一些bib信息有缺失, 这个引用格式对字段要求比较高

**Comment by beyondguo** [comment]
哥们，能请教一下传到overleaf中之后有啥特殊的设置吗？我这里直接传进去显示无法编译

**Comment by zhenweilin** [comment]
设置编译器年份，太新的不行



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月27日 13:33 |
| 收件人 | ***@***.***> |
| 抄送至 | Lin ***@***.***>***@***.***> |
| 主题 | Re: [sijichun/sufethesis] overleaf使用 (Issue #2) |

哥们，能请教一下传到overleaf中之后有啥特殊的设置吗？我这里直接传进去显示无法编译

**Comment by beyondguo** [comment]
感谢回复啊，我看了我这里主要是字体的问题。请问你怎么设置的？之前一直显示 NotFound，于是我把cls文件中的字体部分改成了：

```
\setCJKmainfont{FandolSong}
\setCJKfamilyfont{song}{FandolSong}
\setCJKfamilyfont{hei}{FandolHei}
\setCJKfamilyfont{kai}{FandolKai}
\setCJKfamilyfont{fang}{FandolFang}
```
然后就开始报错
```
You can't pop an empty literal stack for entry Fan2015
You can't pop an empty literal stack for entry Fan2015
You can't pop an empty literal stack for entry NBERw21112
You can't pop an empty literal stack for entry NBERw21460
...
```

**Comment by zhenweilin** [comment]
这个错误我记得应该是无解的，是bib问题，不影响生成的论文，自动忽略就好



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月27日 14:12 |
| 收件人 | ***@***.***> |
| 抄送至 | Lin ***@***.***>***@***.***> |
| 主题 | Re: [sijichun/sufethesis] overleaf使用 (Issue #2) |

感谢回复啊，我看了我这里主要是字体的问题。请问你怎么设置的？之前一直显示 NotFound，于是我把cls文件中的字体部分改成了：

\setCJKmainfont{FandolSong}
\setCJKfamilyfont{song}{FandolSong}
\setCJKfamilyfont{hei}{FandolHei}
\setCJKfamilyfont{kai}{FandolKai}
\setCJKfamilyfont{fang}{FandolFang}


然后就开始报错

You can't pop an empty literal stack for entry Fan2015
You can't pop an empty literal stack for entry Fan2015
You can't pop an empty literal stack for entry NBERw21112
You can't pop an empty literal stack for entry NBERw21460
...

**Comment by beyondguo** [comment]
感谢！
